# ----------- CONFIGURABLE START -----------
title:            "「Hang's blog」|多读书,多看报,多敲代码,多睡觉"
description:      "欢迎来到 「Hang's blog」 | 多读书,多看报,多敲代码,多睡觉"
url:              https://HangForFreedom.github.io # 域名
signoff:          "HangForFreedom" # Your name
facebook_appid:   
google_analytics: UA-101222464-1
share:            true 
baseurl:          "" #根目录
# ---- Where things are ----
source:           .
destination:      ./_site
# 分页
paginate: 12
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  # - name:         首页
  #   url:          /
  #   external:     false
  - name:         Aritcle
    url:          /article
    external:     false
  - name:         Note
    url:          /note
    external:     false
  - name:         Demo
    url:          /demo
    external:     false
  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
