# ----------- CONFIGURABLE START -----------
title:            "Hang Blog|要么牛逼，要么滚蛋"
description:      "Hang Blog|要么牛逼，要么滚蛋"
url:              https://HangForFreedom.github.io # 域名
signoff:          "HangForFreedom" # Your name
facebook_appid:   
google_analytics: UA-101222464-1
share:            true 
baseurl:          "" #根目录
# ---- Where things are ----
source:           .
destination:      ./_site
# 分页
paginate: 12
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  # - name:         首页
  #   url:          /
  #   external:     false
  - name:         Article
    url:          /article
    external:     false
  - name:         Note
    url:          /note
    external:     false
  - name:         Demo
    url:          /demo
    external:     false
  # - name:         Bullshit
  #   url:          /bullshit
  #   external:     false
  # - name:         Archives
  #   url:          /archives
  #   external:     false
  # - name:         Tags
  #   url:          /tags
  #   external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
# ------------ Comments Feature ------------

#gitment
comment_gitment_repo: HangForFreedom.github.io
comment_gitment_clientId: f6f516b227de5009826d
comment_gitment_clientSecret: 73ea9c489b8b12ec43106508b9a5a2e56770e5c7